apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: wisecow #cluster name
  region: ap-south-1 #desired region

nodeGroups:
  - name: ng-1 #cluster node group name
    instanceType: t2.large #desired instance type
    desiredCapacity: 3 #desired nodes count / capacity
    ssh:
      allow: false