apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wisecow-i
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: aef6735fdafa24645a5b9f112620f58b-1324664224.ap-south-1.elb.amazonaws.com  # Replace with your Load Balancer URL
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wisecow-s
            port:
              number: 4499  # Update to your application port
  tls:
  - hosts:
    - aef6735fdafa24645a5b9f112620f58b-1324664224.ap-south-1.elb.amazonaws.com  # Replace with your Load Balancer URL
    secretName: wisecow-tls-secret  # Replace with your actual TLS secret
